ALTER TABLE call_sessions
ADD COLUMN IF NOT EXISTS answered_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS provider_status VARCHAR(50),
ADD COLUMN IF NOT EXISTS charged_minutes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS billing_source VARCHAR(50),
ADD COLUMN IF NOT EXISTS status_callback_payload JSONB;